// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Quic.Templates
{
    using Quic.FPML;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class FxOption : Quic.Templates.Trade
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 3 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
 
  // Run the base template:
  base.TransformText();

            
            #line default
            #line hidden
            this.Write(",");
            
            #line 6 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dtContractStart));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 7 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dtContractEnd));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 8 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dtDelivery));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 9 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strPositionType));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 10 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rAccruedPayoff));
            
            #line default
            #line hidden
            
            #line 11 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
 if (!barrierOption)
	{

            
            #line default
            #line hidden
            this.Write(",");
            
            #line 13 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strPastExercise));
            
            #line default
            #line hidden
            
            #line 14 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
  }

            
            #line default
            #line hidden
            this.Write(",");
            
            #line 15 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rReceiveAmount));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 16 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pYieldInfoReceive));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 17 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pFXInfoReceive));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 18 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rPayAmount));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 19 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pYieldInfoPay));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 20 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pFXInfoPay));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 21 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pYieldInfoSettle));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 22 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pFXInfoSettle));
            
            #line default
            #line hidden
            
            #line 23 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
  BarrierDetails();

            
            #line default
            #line hidden
            this.Write(",");
            
            #line 24 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pImpliedVol));
            
            #line default
            #line hidden
            
            #line 25 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
 if (!barrierOption)
	{

            
            #line default
            #line hidden
            this.Write(",");
            
            #line 27 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rSmileVolOverride));
            
            #line default
            #line hidden
            
            #line 28 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
  }

            
            #line default
            #line hidden
            this.Write(",");
            
            #line 29 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strBusDayConv));
            
            #line default
            #line hidden
            this.Write(",\"");
            
            #line 30 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(putCurrency));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 30 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(callCurrency));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 30 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(settleCurrency));
            
            #line default
            #line hidden
            this.Write("\"");
            
            #line 31 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
 if (doubleBarrier)
	{

            
            #line default
            #line hidden
            this.Write(",FXDoubleBarrierAnalyticSolverPrefs\r\n");
            
            #line 34 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
 } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 35 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"

	protected virtual void BarrierDetails() 
	{
		if (barrierOption)
		{
			if (!doubleBarrier)
			{

        
        #line default
        #line hidden
        
        #line 42 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
this.Write(",");

        
        #line default
        #line hidden
        
        #line 42 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(rBarrier));

        
        #line default
        #line hidden
        
        #line 43 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
this.Write(",");

        
        #line default
        #line hidden
        
        #line 43 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(strBarrierType));

        
        #line default
        #line hidden
        
        #line 44 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
this.Write(",");

        
        #line default
        #line hidden
        
        #line 44 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(strBarrierCondition));

        
        #line default
        #line hidden
        
        #line 45 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
this.Write(",");

        
        #line default
        #line hidden
        
        #line 45 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(rRebate));

        
        #line default
        #line hidden
        
        #line 46 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"

			}
			else {

        
        #line default
        #line hidden
        
        #line 49 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
this.Write(",");

        
        #line default
        #line hidden
        
        #line 49 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(rLBarrier));

        
        #line default
        #line hidden
        
        #line 50 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
this.Write(",");

        
        #line default
        #line hidden
        
        #line 50 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(rUBarrier));

        
        #line default
        #line hidden
        
        #line 51 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
this.Write(",");

        
        #line default
        #line hidden
        
        #line 51 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(strBarrierType));

        
        #line default
        #line hidden
        
        #line 52 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
this.Write(",");

        
        #line default
        #line hidden
        
        #line 52 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(rRebateLower));

        
        #line default
        #line hidden
        
        #line 53 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
this.Write(",");

        
        #line default
        #line hidden
        
        #line 53 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(rRebateUpper));

        
        #line default
        #line hidden
        
        #line 54 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"

			}

        
        #line default
        #line hidden
        
        #line 56 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
this.Write(",");

        
        #line default
        #line hidden
        
        #line 56 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(strRebatePaymentType));

        
        #line default
        #line hidden
        
        #line 57 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
this.Write(",");

        
        #line default
        #line hidden
        
        #line 57 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(strSamplingFrequency));

        
        #line default
        #line hidden
        
        #line 58 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
this.Write(",");

        
        #line default
        #line hidden
        
        #line 58 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(nViolation));

        
        #line default
        #line hidden
        
        #line 59 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
this.Write(",");

        
        #line default
        #line hidden
        
        #line 59 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dtBarrierBreach));

        
        #line default
        #line hidden
        
        #line 60 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxOption.tt"
 
		}
	}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
