// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Quic.Templates
{
    using Quic.FPML;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxSingleLeg.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class FxSingleLeg : Quic.Templates.Trade
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 3 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxSingleLeg.tt"
 
  // Run the base template:
  base.TransformText();

            
            #line default
            #line hidden
            this.Write(",");
            
            #line 6 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxSingleLeg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dtDelivery));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 7 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxSingleLeg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rReceiveAmount));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 8 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxSingleLeg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pYieldInfoReceive));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 9 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxSingleLeg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pFXInfoReceive));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 10 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxSingleLeg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rPayAmount));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 11 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxSingleLeg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pYieldInfoPay));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 12 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxSingleLeg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pFXInfoPay));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 13 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxSingleLeg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strBusDayConv));
            
            #line default
            #line hidden
            this.Write(",\"");
            
            #line 14 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxSingleLeg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strCurrency1));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 14 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\FX\FxSingleLeg.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strCurrency2));
            
            #line default
            #line hidden
            this.Write(",USD\" \r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
