// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Quic.Templates
{
    using Quic.FPML;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\BulletPayment.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class BulletPayment : Quic.Templates.TradeMap
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 3 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\BulletPayment.tt"
 
  // Run the base template:
  base.TransformText();

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 7 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\BulletPayment.tt"

protected override void GetMapType()
{

        
        #line default
        #line hidden
        
        #line 10 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\BulletPayment.tt"
this.Write("\tstrType, S, Bullet\r\n");

        
        #line default
        #line hidden
        
        #line 12 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\BulletPayment.tt"

}
protected override void MapDetails()
{

        
        #line default
        #line hidden
        
        #line 16 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\BulletPayment.tt"
this.Write("\tstrCurrency, S, ");

        
        #line default
        #line hidden
        
        #line 17 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\BulletPayment.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(strCurrency));

        
        #line default
        #line hidden
        
        #line 17 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\BulletPayment.tt"
this.Write("\r\n\tadtPayment, AD,  ");

        
        #line default
        #line hidden
        
        #line 18 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\BulletPayment.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(adtPayment));

        
        #line default
        #line hidden
        
        #line 18 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\BulletPayment.tt"
this.Write("\r\n\tarAmount, AR, ");

        
        #line default
        #line hidden
        
        #line 19 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\BulletPayment.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(arAmount));

        
        #line default
        #line hidden
        
        #line 19 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\BulletPayment.tt"
this.Write("\r\n\tpYieldInfo, C, ");

        
        #line default
        #line hidden
        
        #line 20 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\BulletPayment.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(strCurrency));

        
        #line default
        #line hidden
        
        #line 20 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\BulletPayment.tt"
this.Write(".Yield.");

        
        #line default
        #line hidden
        
        #line 20 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\BulletPayment.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(strCurrency));

        
        #line default
        #line hidden
        
        #line 20 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\BulletPayment.tt"
this.Write("\r\n\tpFXInfo, C, ");

        
        #line default
        #line hidden
        
        #line 21 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\BulletPayment.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(strCurrency));

        
        #line default
        #line hidden
        
        #line 21 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\BulletPayment.tt"
this.Write(".Exchange.USD\r\n");

        
        #line default
        #line hidden
        
        #line 22 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\BulletPayment.tt"

}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
