// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Quic.Templates
{
    using Quic.FPML;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\Swap.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class Swap : Quic.Templates.Trade
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 3 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\Swap.tt"
 
  // Run the base template:
  base.TransformText();

            
            #line default
            #line hidden
            this.Write(",");
            
            #line 6 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\Swap.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strLeg1Name));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 6 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\Swap.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strLeg2Name));
            
            #line default
            #line hidden
            this.Write(",,\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
