// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Quic.Templates
{
    using Quic.FPML;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class SwapLeg : Quic.Templates.TradeMap
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 3 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"
 
  // Run the base template:
  base.TransformText();

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 7 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"

	protected override void GetMapType() {}
	protected virtual void LegDetails() {}
	protected override void MapDetails() 
	{

        
        #line default
        #line hidden
        
        #line 12 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"
this.Write("\tstrCurrency, S, ");

        
        #line default
        #line hidden
        
        #line 13 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(strCurrency));

        
        #line default
        #line hidden
        
        #line 13 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"
this.Write("\r\n");

        
        #line default
        #line hidden
        
        #line 14 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"

	if (!swaptionOverride)
    {

        
        #line default
        #line hidden
        
        #line 17 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"
this.Write("\tstrNotionalExchange, S, ");

        
        #line default
        #line hidden
        
        #line 18 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(strNotionalExchange));

        
        #line default
        #line hidden
        
        #line 18 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"
this.Write("\r\n");

        
        #line default
        #line hidden
        
        #line 19 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"

	}

        
        #line default
        #line hidden
        
        #line 21 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"
this.Write("\tarNotional, AR,  ");

        
        #line default
        #line hidden
        
        #line 22 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(arNotional));

        
        #line default
        #line hidden
        
        #line 22 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"
this.Write("\r\n\tadtStart, AD,  ");

        
        #line default
        #line hidden
        
        #line 23 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(adtStart));

        
        #line default
        #line hidden
        
        #line 23 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"
this.Write("\r\n\tadtEnd, AD,  ");

        
        #line default
        #line hidden
        
        #line 24 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(adtEnd));

        
        #line default
        #line hidden
        
        #line 24 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"
this.Write("\r\n\tadtPayment, AD,  ");

        
        #line default
        #line hidden
        
        #line 25 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(adtPayment));

        
        #line default
        #line hidden
        
        #line 25 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"
this.Write("\r\n\tstrBusDayConv, S, ");

        
        #line default
        #line hidden
        
        #line 26 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(strBusDayConv));

        
        #line default
        #line hidden
        
        #line 26 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"
this.Write("\r\n\tstrDaycount, S, ");

        
        #line default
        #line hidden
        
        #line 27 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(strDaycount));

        
        #line default
        #line hidden
        
        #line 27 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"
this.Write("\r\n");

        
        #line default
        #line hidden
        
        #line 28 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"

	LegDetails();

        
        #line default
        #line hidden
        
        #line 30 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"
this.Write("\tpYieldInfo, C, ");

        
        #line default
        #line hidden
        
        #line 31 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(Utilities.YieldCurve(strCurrency, xccyFlag)));

        
        #line default
        #line hidden
        
        #line 31 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"
this.Write("\r\n\tpFXInfo, C, ");

        
        #line default
        #line hidden
        
        #line 32 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(strCurrency));

        
        #line default
        #line hidden
        
        #line 32 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"
this.Write(".Exchange.USD\r\n");

        
        #line default
        #line hidden
        
        #line 33 "D:\QuIC\etl\code\Quic.WebService\Quic.Templates\IR\Swap\SwapLeg.tt"

	}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
