//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quic.Dispatch.ResourceManager {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobStatus", Namespace="Quic.Dispatch.WebService")]
    [System.SerializableAttribute()]
    public partial class JobStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Quic.Dispatch.ResourceManager.FunctionStatus funcStatusField;
        
        private double progressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string progressMsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Quic.Dispatch.ResourceManager.FunctionStatus funcStatus {
            get {
                return this.funcStatusField;
            }
            set {
                if ((this.funcStatusField.Equals(value) != true)) {
                    this.funcStatusField = value;
                    this.RaisePropertyChanged("funcStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double progress {
            get {
                return this.progressField;
            }
            set {
                if ((this.progressField.Equals(value) != true)) {
                    this.progressField = value;
                    this.RaisePropertyChanged("progress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string progressMsg {
            get {
                return this.progressMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.progressMsgField, value) != true)) {
                    this.progressMsgField = value;
                    this.RaisePropertyChanged("progressMsg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FunctionStatus", Namespace="Quic.Dispatch.WebService")]
    public enum FunctionStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Queued = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Running = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelled = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Quic.Dispatch.WebService", ConfigurationName="ResourceManager.IQuicDispatchInterface")]
    public interface IQuicDispatchInterface {
        
        // CODEGEN: Generating message contract since element name strModulePaths from namespace Quic.Dispatch.WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Quic.Dispatch.WebService/IQuicDispatchInterface/Submit", ReplyAction="Quic.Dispatch.WebService/IQuicDispatchInterface/SubmitResponse")]
        Quic.Dispatch.ResourceManager.SubmitResponse Submit(Quic.Dispatch.ResourceManager.SubmitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Quic.Dispatch.WebService/IQuicDispatchInterface/Submit", ReplyAction="Quic.Dispatch.WebService/IQuicDispatchInterface/SubmitResponse")]
        System.Threading.Tasks.Task<Quic.Dispatch.ResourceManager.SubmitResponse> SubmitAsync(Quic.Dispatch.ResourceManager.SubmitRequest request);
        
        // CODEGEN: Generating message contract since element name strModulePaths from namespace Quic.Dispatch.WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Quic.Dispatch.WebService/IQuicDispatchInterface/SubmitEx", ReplyAction="Quic.Dispatch.WebService/IQuicDispatchInterface/SubmitExResponse")]
        Quic.Dispatch.ResourceManager.SubmitExResponse SubmitEx(Quic.Dispatch.ResourceManager.SubmitExRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Quic.Dispatch.WebService/IQuicDispatchInterface/SubmitEx", ReplyAction="Quic.Dispatch.WebService/IQuicDispatchInterface/SubmitExResponse")]
        System.Threading.Tasks.Task<Quic.Dispatch.ResourceManager.SubmitExResponse> SubmitExAsync(Quic.Dispatch.ResourceManager.SubmitExRequest request);
        
        // CODEGEN: Generating message contract since element name GetStatusResult from namespace Quic.Dispatch.WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Quic.Dispatch.WebService/IQuicDispatchInterface/GetStatus", ReplyAction="Quic.Dispatch.WebService/IQuicDispatchInterface/GetStatusResponse")]
        Quic.Dispatch.ResourceManager.GetStatusResponse GetStatus(Quic.Dispatch.ResourceManager.GetStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Quic.Dispatch.WebService/IQuicDispatchInterface/GetStatus", ReplyAction="Quic.Dispatch.WebService/IQuicDispatchInterface/GetStatusResponse")]
        System.Threading.Tasks.Task<Quic.Dispatch.ResourceManager.GetStatusResponse> GetStatusAsync(Quic.Dispatch.ResourceManager.GetStatusRequest request);
        
        // CODEGEN: Generating message contract since element name GetResultsResult from namespace Quic.Dispatch.WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Quic.Dispatch.WebService/IQuicDispatchInterface/GetResults", ReplyAction="Quic.Dispatch.WebService/IQuicDispatchInterface/GetResultsResponse")]
        Quic.Dispatch.ResourceManager.GetResultsResponse GetResults(Quic.Dispatch.ResourceManager.GetResultsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Quic.Dispatch.WebService/IQuicDispatchInterface/GetResults", ReplyAction="Quic.Dispatch.WebService/IQuicDispatchInterface/GetResultsResponse")]
        System.Threading.Tasks.Task<Quic.Dispatch.ResourceManager.GetResultsResponse> GetResultsAsync(Quic.Dispatch.ResourceManager.GetResultsRequest request);
        
        // CODEGEN: Generating message contract since element name GetErrorResult from namespace Quic.Dispatch.WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Quic.Dispatch.WebService/IQuicDispatchInterface/GetError", ReplyAction="Quic.Dispatch.WebService/IQuicDispatchInterface/GetErrorResponse")]
        Quic.Dispatch.ResourceManager.GetErrorResponse GetError(Quic.Dispatch.ResourceManager.GetErrorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Quic.Dispatch.WebService/IQuicDispatchInterface/GetError", ReplyAction="Quic.Dispatch.WebService/IQuicDispatchInterface/GetErrorResponse")]
        System.Threading.Tasks.Task<Quic.Dispatch.ResourceManager.GetErrorResponse> GetErrorAsync(Quic.Dispatch.ResourceManager.GetErrorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Quic.Dispatch.WebService/IQuicDispatchInterface/Cancel", ReplyAction="Quic.Dispatch.WebService/IQuicDispatchInterface/CancelResponse")]
        void Cancel(ulong jobId);
        
        [System.ServiceModel.OperationContractAttribute(Action="Quic.Dispatch.WebService/IQuicDispatchInterface/Cancel", ReplyAction="Quic.Dispatch.WebService/IQuicDispatchInterface/CancelResponse")]
        System.Threading.Tasks.Task CancelAsync(ulong jobId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Submit", Namespace="Quic.Dispatch.WebService", Order=0)]
        public Quic.Dispatch.ResourceManager.SubmitRequestBody Body;
        
        public SubmitRequest() {
        }
        
        public SubmitRequest(Quic.Dispatch.ResourceManager.SubmitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Quic.Dispatch.WebService")]
    public partial class SubmitRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strModulePaths;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strModuleName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strModuleVersion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strFunctionXml;
        
        public SubmitRequestBody() {
        }
        
        public SubmitRequestBody(string strModulePaths, string strModuleName, string strModuleVersion, string strFunctionXml) {
            this.strModulePaths = strModulePaths;
            this.strModuleName = strModuleName;
            this.strModuleVersion = strModuleVersion;
            this.strFunctionXml = strFunctionXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitResponse", Namespace="Quic.Dispatch.WebService", Order=0)]
        public Quic.Dispatch.ResourceManager.SubmitResponseBody Body;
        
        public SubmitResponse() {
        }
        
        public SubmitResponse(Quic.Dispatch.ResourceManager.SubmitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Quic.Dispatch.WebService")]
    public partial class SubmitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ulong SubmitResult;
        
        public SubmitResponseBody() {
        }
        
        public SubmitResponseBody(ulong SubmitResult) {
            this.SubmitResult = SubmitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitEx", Namespace="Quic.Dispatch.WebService", Order=0)]
        public Quic.Dispatch.ResourceManager.SubmitExRequestBody Body;
        
        public SubmitExRequest() {
        }
        
        public SubmitExRequest(Quic.Dispatch.ResourceManager.SubmitExRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Quic.Dispatch.WebService")]
    public partial class SubmitExRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strModulePaths;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strModuleName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strModuleVersion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strFunctionXml;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int priority;
        
        public SubmitExRequestBody() {
        }
        
        public SubmitExRequestBody(string strModulePaths, string strModuleName, string strModuleVersion, string strFunctionXml, int priority) {
            this.strModulePaths = strModulePaths;
            this.strModuleName = strModuleName;
            this.strModuleVersion = strModuleVersion;
            this.strFunctionXml = strFunctionXml;
            this.priority = priority;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitExResponse", Namespace="Quic.Dispatch.WebService", Order=0)]
        public Quic.Dispatch.ResourceManager.SubmitExResponseBody Body;
        
        public SubmitExResponse() {
        }
        
        public SubmitExResponse(Quic.Dispatch.ResourceManager.SubmitExResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Quic.Dispatch.WebService")]
    public partial class SubmitExResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ulong SubmitExResult;
        
        public SubmitExResponseBody() {
        }
        
        public SubmitExResponseBody(ulong SubmitExResult) {
            this.SubmitExResult = SubmitExResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatus", Namespace="Quic.Dispatch.WebService", Order=0)]
        public Quic.Dispatch.ResourceManager.GetStatusRequestBody Body;
        
        public GetStatusRequest() {
        }
        
        public GetStatusRequest(Quic.Dispatch.ResourceManager.GetStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Quic.Dispatch.WebService")]
    public partial class GetStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ulong jobId;
        
        public GetStatusRequestBody() {
        }
        
        public GetStatusRequestBody(ulong jobId) {
            this.jobId = jobId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatusResponse", Namespace="Quic.Dispatch.WebService", Order=0)]
        public Quic.Dispatch.ResourceManager.GetStatusResponseBody Body;
        
        public GetStatusResponse() {
        }
        
        public GetStatusResponse(Quic.Dispatch.ResourceManager.GetStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Quic.Dispatch.WebService")]
    public partial class GetStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Quic.Dispatch.ResourceManager.JobStatus GetStatusResult;
        
        public GetStatusResponseBody() {
        }
        
        public GetStatusResponseBody(Quic.Dispatch.ResourceManager.JobStatus GetStatusResult) {
            this.GetStatusResult = GetStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResults", Namespace="Quic.Dispatch.WebService", Order=0)]
        public Quic.Dispatch.ResourceManager.GetResultsRequestBody Body;
        
        public GetResultsRequest() {
        }
        
        public GetResultsRequest(Quic.Dispatch.ResourceManager.GetResultsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Quic.Dispatch.WebService")]
    public partial class GetResultsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ulong jobId;
        
        public GetResultsRequestBody() {
        }
        
        public GetResultsRequestBody(ulong jobId) {
            this.jobId = jobId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResultsResponse", Namespace="Quic.Dispatch.WebService", Order=0)]
        public Quic.Dispatch.ResourceManager.GetResultsResponseBody Body;
        
        public GetResultsResponse() {
        }
        
        public GetResultsResponse(Quic.Dispatch.ResourceManager.GetResultsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Quic.Dispatch.WebService")]
    public partial class GetResultsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetResultsResult;
        
        public GetResultsResponseBody() {
        }
        
        public GetResultsResponseBody(string GetResultsResult) {
            this.GetResultsResult = GetResultsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetErrorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetError", Namespace="Quic.Dispatch.WebService", Order=0)]
        public Quic.Dispatch.ResourceManager.GetErrorRequestBody Body;
        
        public GetErrorRequest() {
        }
        
        public GetErrorRequest(Quic.Dispatch.ResourceManager.GetErrorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Quic.Dispatch.WebService")]
    public partial class GetErrorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ulong jobId;
        
        public GetErrorRequestBody() {
        }
        
        public GetErrorRequestBody(ulong jobId) {
            this.jobId = jobId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetErrorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetErrorResponse", Namespace="Quic.Dispatch.WebService", Order=0)]
        public Quic.Dispatch.ResourceManager.GetErrorResponseBody Body;
        
        public GetErrorResponse() {
        }
        
        public GetErrorResponse(Quic.Dispatch.ResourceManager.GetErrorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Quic.Dispatch.WebService")]
    public partial class GetErrorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetErrorResult;
        
        public GetErrorResponseBody() {
        }
        
        public GetErrorResponseBody(string GetErrorResult) {
            this.GetErrorResult = GetErrorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQuicDispatchInterfaceChannel : Quic.Dispatch.ResourceManager.IQuicDispatchInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuicDispatchInterfaceClient : System.ServiceModel.ClientBase<Quic.Dispatch.ResourceManager.IQuicDispatchInterface>, Quic.Dispatch.ResourceManager.IQuicDispatchInterface {
        
        public QuicDispatchInterfaceClient() {
        }
        
        public QuicDispatchInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuicDispatchInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuicDispatchInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuicDispatchInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quic.Dispatch.ResourceManager.SubmitResponse Quic.Dispatch.ResourceManager.IQuicDispatchInterface.Submit(Quic.Dispatch.ResourceManager.SubmitRequest request) {
            return base.Channel.Submit(request);
        }
        
        public ulong Submit(string strModulePaths, string strModuleName, string strModuleVersion, string strFunctionXml) {
            Quic.Dispatch.ResourceManager.SubmitRequest inValue = new Quic.Dispatch.ResourceManager.SubmitRequest();
            inValue.Body = new Quic.Dispatch.ResourceManager.SubmitRequestBody();
            inValue.Body.strModulePaths = strModulePaths;
            inValue.Body.strModuleName = strModuleName;
            inValue.Body.strModuleVersion = strModuleVersion;
            inValue.Body.strFunctionXml = strFunctionXml;
            Quic.Dispatch.ResourceManager.SubmitResponse retVal = ((Quic.Dispatch.ResourceManager.IQuicDispatchInterface)(this)).Submit(inValue);
            return retVal.Body.SubmitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Quic.Dispatch.ResourceManager.SubmitResponse> Quic.Dispatch.ResourceManager.IQuicDispatchInterface.SubmitAsync(Quic.Dispatch.ResourceManager.SubmitRequest request) {
            return base.Channel.SubmitAsync(request);
        }
        
        public System.Threading.Tasks.Task<Quic.Dispatch.ResourceManager.SubmitResponse> SubmitAsync(string strModulePaths, string strModuleName, string strModuleVersion, string strFunctionXml) {
            Quic.Dispatch.ResourceManager.SubmitRequest inValue = new Quic.Dispatch.ResourceManager.SubmitRequest();
            inValue.Body = new Quic.Dispatch.ResourceManager.SubmitRequestBody();
            inValue.Body.strModulePaths = strModulePaths;
            inValue.Body.strModuleName = strModuleName;
            inValue.Body.strModuleVersion = strModuleVersion;
            inValue.Body.strFunctionXml = strFunctionXml;
            return ((Quic.Dispatch.ResourceManager.IQuicDispatchInterface)(this)).SubmitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quic.Dispatch.ResourceManager.SubmitExResponse Quic.Dispatch.ResourceManager.IQuicDispatchInterface.SubmitEx(Quic.Dispatch.ResourceManager.SubmitExRequest request) {
            return base.Channel.SubmitEx(request);
        }
        
        public ulong SubmitEx(string strModulePaths, string strModuleName, string strModuleVersion, string strFunctionXml, int priority) {
            Quic.Dispatch.ResourceManager.SubmitExRequest inValue = new Quic.Dispatch.ResourceManager.SubmitExRequest();
            inValue.Body = new Quic.Dispatch.ResourceManager.SubmitExRequestBody();
            inValue.Body.strModulePaths = strModulePaths;
            inValue.Body.strModuleName = strModuleName;
            inValue.Body.strModuleVersion = strModuleVersion;
            inValue.Body.strFunctionXml = strFunctionXml;
            inValue.Body.priority = priority;
            Quic.Dispatch.ResourceManager.SubmitExResponse retVal = ((Quic.Dispatch.ResourceManager.IQuicDispatchInterface)(this)).SubmitEx(inValue);
            return retVal.Body.SubmitExResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Quic.Dispatch.ResourceManager.SubmitExResponse> Quic.Dispatch.ResourceManager.IQuicDispatchInterface.SubmitExAsync(Quic.Dispatch.ResourceManager.SubmitExRequest request) {
            return base.Channel.SubmitExAsync(request);
        }
        
        public System.Threading.Tasks.Task<Quic.Dispatch.ResourceManager.SubmitExResponse> SubmitExAsync(string strModulePaths, string strModuleName, string strModuleVersion, string strFunctionXml, int priority) {
            Quic.Dispatch.ResourceManager.SubmitExRequest inValue = new Quic.Dispatch.ResourceManager.SubmitExRequest();
            inValue.Body = new Quic.Dispatch.ResourceManager.SubmitExRequestBody();
            inValue.Body.strModulePaths = strModulePaths;
            inValue.Body.strModuleName = strModuleName;
            inValue.Body.strModuleVersion = strModuleVersion;
            inValue.Body.strFunctionXml = strFunctionXml;
            inValue.Body.priority = priority;
            return ((Quic.Dispatch.ResourceManager.IQuicDispatchInterface)(this)).SubmitExAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quic.Dispatch.ResourceManager.GetStatusResponse Quic.Dispatch.ResourceManager.IQuicDispatchInterface.GetStatus(Quic.Dispatch.ResourceManager.GetStatusRequest request) {
            return base.Channel.GetStatus(request);
        }
        
        public Quic.Dispatch.ResourceManager.JobStatus GetStatus(ulong jobId) {
            Quic.Dispatch.ResourceManager.GetStatusRequest inValue = new Quic.Dispatch.ResourceManager.GetStatusRequest();
            inValue.Body = new Quic.Dispatch.ResourceManager.GetStatusRequestBody();
            inValue.Body.jobId = jobId;
            Quic.Dispatch.ResourceManager.GetStatusResponse retVal = ((Quic.Dispatch.ResourceManager.IQuicDispatchInterface)(this)).GetStatus(inValue);
            return retVal.Body.GetStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Quic.Dispatch.ResourceManager.GetStatusResponse> Quic.Dispatch.ResourceManager.IQuicDispatchInterface.GetStatusAsync(Quic.Dispatch.ResourceManager.GetStatusRequest request) {
            return base.Channel.GetStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<Quic.Dispatch.ResourceManager.GetStatusResponse> GetStatusAsync(ulong jobId) {
            Quic.Dispatch.ResourceManager.GetStatusRequest inValue = new Quic.Dispatch.ResourceManager.GetStatusRequest();
            inValue.Body = new Quic.Dispatch.ResourceManager.GetStatusRequestBody();
            inValue.Body.jobId = jobId;
            return ((Quic.Dispatch.ResourceManager.IQuicDispatchInterface)(this)).GetStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quic.Dispatch.ResourceManager.GetResultsResponse Quic.Dispatch.ResourceManager.IQuicDispatchInterface.GetResults(Quic.Dispatch.ResourceManager.GetResultsRequest request) {
            return base.Channel.GetResults(request);
        }
        
        public string GetResults(ulong jobId) {
            Quic.Dispatch.ResourceManager.GetResultsRequest inValue = new Quic.Dispatch.ResourceManager.GetResultsRequest();
            inValue.Body = new Quic.Dispatch.ResourceManager.GetResultsRequestBody();
            inValue.Body.jobId = jobId;
            Quic.Dispatch.ResourceManager.GetResultsResponse retVal = ((Quic.Dispatch.ResourceManager.IQuicDispatchInterface)(this)).GetResults(inValue);
            return retVal.Body.GetResultsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Quic.Dispatch.ResourceManager.GetResultsResponse> Quic.Dispatch.ResourceManager.IQuicDispatchInterface.GetResultsAsync(Quic.Dispatch.ResourceManager.GetResultsRequest request) {
            return base.Channel.GetResultsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Quic.Dispatch.ResourceManager.GetResultsResponse> GetResultsAsync(ulong jobId) {
            Quic.Dispatch.ResourceManager.GetResultsRequest inValue = new Quic.Dispatch.ResourceManager.GetResultsRequest();
            inValue.Body = new Quic.Dispatch.ResourceManager.GetResultsRequestBody();
            inValue.Body.jobId = jobId;
            return ((Quic.Dispatch.ResourceManager.IQuicDispatchInterface)(this)).GetResultsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quic.Dispatch.ResourceManager.GetErrorResponse Quic.Dispatch.ResourceManager.IQuicDispatchInterface.GetError(Quic.Dispatch.ResourceManager.GetErrorRequest request) {
            return base.Channel.GetError(request);
        }
        
        public string GetError(ulong jobId) {
            Quic.Dispatch.ResourceManager.GetErrorRequest inValue = new Quic.Dispatch.ResourceManager.GetErrorRequest();
            inValue.Body = new Quic.Dispatch.ResourceManager.GetErrorRequestBody();
            inValue.Body.jobId = jobId;
            Quic.Dispatch.ResourceManager.GetErrorResponse retVal = ((Quic.Dispatch.ResourceManager.IQuicDispatchInterface)(this)).GetError(inValue);
            return retVal.Body.GetErrorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Quic.Dispatch.ResourceManager.GetErrorResponse> Quic.Dispatch.ResourceManager.IQuicDispatchInterface.GetErrorAsync(Quic.Dispatch.ResourceManager.GetErrorRequest request) {
            return base.Channel.GetErrorAsync(request);
        }
        
        public System.Threading.Tasks.Task<Quic.Dispatch.ResourceManager.GetErrorResponse> GetErrorAsync(ulong jobId) {
            Quic.Dispatch.ResourceManager.GetErrorRequest inValue = new Quic.Dispatch.ResourceManager.GetErrorRequest();
            inValue.Body = new Quic.Dispatch.ResourceManager.GetErrorRequestBody();
            inValue.Body.jobId = jobId;
            return ((Quic.Dispatch.ResourceManager.IQuicDispatchInterface)(this)).GetErrorAsync(inValue);
        }
        
        public void Cancel(ulong jobId) {
            base.Channel.Cancel(jobId);
        }
        
        public System.Threading.Tasks.Task CancelAsync(ulong jobId) {
            return base.Channel.CancelAsync(jobId);
        }
    }
}
